[build]
    functions = "endpoints"
    command = "netlify-lambda install && mkdir ./public && yum install libuuid-devel libmount-devel && cp /lib64/{libuuid,libmount,libblkid}.so.1 node_modules/canvas/build/Release/"