[build]
    functions = "endpoints"
    command = "netlify-lambda install"
[[redirects]]
  from = "https://covbot.netlify.app/"
  to = "https://arogueotaku.github.io/covBot/"
  status = 301
  force = true