[build]
    functions = "endpoints"
    command = "apt-get install libuuid-devel libmount-devel && apt-get update && cp /lib64/{libuuid,libmount,libblkid}.so.1 node_modules/canvas/build/Release/ && netlify-lambda install"